kind: Deployment
apiVersion: apps/v1
metadata:
  name: forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: forward-auth
  template:
    metadata:
      labels:
        name: forward-auth
    spec:
      containers:
        - image: lowet84/traefik-forward-auth
          name: forward-auth
          env:
            - name: CLIENT_ID
              value: traefik
            - name: CLIENT_SECRET
              value: 9ac09cc7-cf3e-4969-a8c4-aadbda2dffc3
            - name: PROVIDER_URI
              value: https://auth.fredriklowenhamn.se/auth/realms/master
            - name: SECRET
              value: supersecretstring