kind: Deployment
apiVersion: apps/v1
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak
  template:
    metadata:
      labels:
        name: keycloak
    spec:
      containers:
        - image: jboss/keycloak
          name: keycloak
          env:
            - name: KEYCLOAK_USER
              value: fredrik
            - name: KEYCLOAK_PASSWORD
              value: gurkburk
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
