apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-share
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/filer/Settings/keycloak"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-share
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: keycloak-share
