kind: Deployment
apiVersion: apps/v1
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nexus
  template:
    metadata:
      labels:
        name: nexus
    spec:
      containers:
        - image: sonatype/nexus3
          name: nexus
          volumeMounts:
            - name: nexus-share
              mountPath: /nexus-data
      volumes:
        - name: nexus-share
          persistentVolumeClaim:
            claimName: nexus-share
